source ${HOME}/virtualenv_gpu/bin/activate
cd im2txt-workspace

# Path to checkpoint file or a directory containing checkpoint files. Passing
# a directory will only work if there is also a file named 'checkpoint' which
# lists the available checkpoints in the directory. It will not work if you
# point to a directory with just a copy of a model checkpoint: in that case,
# you will need to pass the checkpoint path explicitly.
CHECKPOINT_PATH="${HOME}/im2txt/model/train/model-renamed.ckpt-2000000"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="${HOME}/im2txt/model/word_counts2.txt"

# JPEG image file to caption.
#IMAGE_FILE="${HOME}/mscoco/raw-data/val2014/COCO_val2014_000000224477.jpg"
IMAGE_FOLDER="${HOME}/scam-images-by-type-singlefile/scam/*" # "${HOME}/scam-images-by-type/real/*" #"${HOME}/scam-images-by-type/scam/*"
OUTPUT_FOLDER="${HOME}/scam-im2txt-by-type-singlefile/scam"  # "${HOME}/scam-im2txt-by-type/real"   #"${HOME}/scam-im2txt-by-type/scam"

# Build the inference binary.
bazel build -c opt im2txt/run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
export CUDA_VISIBLE_DEVICES=""

for f in $IMAGE_FOLDER
do
	FILE_NAME=$(basename $f)

	echo "Processing $f"

	# Run inference to generate captions.
	bazel-bin/im2txt/run_inference \
	  --checkpoint_path=${CHECKPOINT_PATH} \
	  --vocab_file=${VOCAB_FILE} \
	  --input_files=${f} > ${OUTPUT_FOLDER}/${FILE_NAME}.txt

done

cd ..